// Copyright (c) 2026 The Ycash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

// Price attestations (v3 plan §3.8 BUNDLE-1, W3, R13, R17): the message
// layout and compact low-S verification against the known-answer vectors of
// src/test/data/yellowback_attest_vectors.json (generated by
// src/test/gen_yellowback_attest_vectors.py; the Python framework and the
// Rust agent must reproduce them), the 74-byte codec, and the rejections:
// high-S, wrong block hash, wrong key, tampered fields.

#include "yellowback/attest.h"

#include "crypto/sha256.h"
#include "key.h"
#include "test/data/yellowback_attest_vectors.json.h"
#include "test/test_bitcoin.h"
#include "univalue.h"
#include "util/strencodings.h"

#include <boost/test/unit_test.hpp>

#include <set>

using namespace yellowback;

namespace {

UniValue Vectors()
{
    UniValue doc;
    BOOST_REQUIRE(doc.read(std::string(json_tests::yellowback_attest_vectors, json_tests::yellowback_attest_vectors + sizeof(json_tests::yellowback_attest_vectors))));
    return doc;
}

std::array<unsigned char, 64> Sig64(const std::string& hex)
{
    std::vector<unsigned char> v = ParseHex(hex);
    BOOST_REQUIRE_EQUAL(v.size(), 64u);
    std::array<unsigned char, 64> out;
    std::copy(v.begin(), v.end(), out.begin());
    return out;
}

uint256 Internal32(const std::string& hex)
{
    std::vector<unsigned char> v = ParseHex(hex);
    BOOST_REQUIRE_EQUAL(v.size(), 32u);
    return uint256(v);
}

} // namespace

BOOST_FIXTURE_TEST_SUITE(yellowback_attest_tests, BasicTestingSetup)

// Rule: BUNDLE-1
BOOST_AUTO_TEST_CASE(message_layout)
{
    // SHA256("YBATTEST1" || seq LE16 || price LE32 || citedHeight LE32 || blockHash internal bytes): 51 bytes, no length byte.
    uint256 bh;
    for (int i = 0; i < 32; i++) *(bh.begin() + i) = (unsigned char)i;
    std::vector<unsigned char> pre = { 'Y', 'B', 'A', 'T', 'T', 'E', 'S', 'T', '1',
                                       0x34, 0x12,
                                       0x78, 0x56, 0x34, 0x12,
                                       0x21, 0x43, 0x65, 0x07 };
    pre.insert(pre.end(), bh.begin(), bh.end());
    BOOST_REQUIRE_EQUAL(pre.size(), 51u);
    uint256 expect;
    CSHA256().Write(pre.data(), pre.size()).Finalize(expect.begin());
    BOOST_CHECK(AttestMessage(0x1234, 0x12345678, 0x07654321, bh) == expect);
    // Every field is bound.
    BOOST_CHECK(AttestMessage(0x1235, 0x12345678, 0x07654321, bh) != expect);
    BOOST_CHECK(AttestMessage(0x1234, 0x12345679, 0x07654321, bh) != expect);
    BOOST_CHECK(AttestMessage(0x1234, 0x12345678, 0x07654322, bh) != expect);
    uint256 other = bh;
    *other.begin() ^= 1;
    BOOST_CHECK(AttestMessage(0x1234, 0x12345678, 0x07654321, other) != expect);
    // The vectors' messages.
    UniValue doc = Vectors();
    BOOST_CHECK_EQUAL(doc["prefix"].get_str(), "YBATTEST1");
    for (const UniValue& v : doc["valid"].getValues()) {
        uint256 msg = AttestMessage(v["seq"].get_int(), (uint32_t)v["priceMicroUsd"].get_int64(), (uint32_t)v["citedHeight"].get_int64(),
                                    Internal32(v["blockHashInternal"].get_str()));
        BOOST_CHECK_EQUAL(HexStr(msg.begin(), msg.end()), v["message"].get_str());
        // The displayed form is the reversed hex of the internal bytes.
        BOOST_CHECK_EQUAL(Internal32(v["blockHashInternal"].get_str()).GetHex(), v["blockHash"].get_str());
    }
}

// Rule: BUNDLE-1
BOOST_AUTO_TEST_CASE(vectors_verify)
{
    UniValue doc = Vectors();
    BOOST_REQUIRE_EQUAL(doc["valid"].size(), 8u);   // seq 0..5 once each, then seq 0 and 1 again
    BOOST_REQUIRE_EQUAL(doc["keys"].size(), 6u);
    // The pubkeys are what CKey derives from the secrets.
    for (const UniValue& k : doc["keys"].getValues()) {
        std::vector<unsigned char> secret = ParseHex(k["secret"].get_str());
        CKey key;
        key.Set(secret.begin(), secret.end(), true);
        BOOST_REQUIRE(key.IsValid());
        BOOST_CHECK_EQUAL(HexStr(key.GetPubKey()), k["pubkey"].get_str());
    }
    for (const UniValue& v : doc["valid"].getValues()) {
        const uint256 msg = Internal32(v["message"].get_str());
        const CPubKey pk(ParseHex(v["pubkey"].get_str()));
        const std::array<unsigned char, 64> sig = Sig64(v["sig"].get_str());
        BOOST_CHECK_MESSAGE(VerifyCompactSig(pk, msg, sig), "seq " + std::to_string(v["seq"].get_int()));
        // libsecp256k1's own deterministic signature (RFC 6979, no extra data) is the vector's, so
        // CKey::Sign of the same message re-derives it: the generator's arithmetic matches the library.
        for (const UniValue& k : doc["keys"].getValues()) {
            if (k["seq"].get_int() != v["seq"].get_int()) continue;
            std::vector<unsigned char> secret = ParseHex(k["secret"].get_str());
            CKey key;
            key.Set(secret.begin(), secret.end(), true);
            std::vector<unsigned char> der;
            BOOST_REQUIRE(key.Sign(msg, der));
            // DER -> compact: r and s are the two INTEGERs, stripped of the sign padding.
            std::array<unsigned char, 64> compact;
            compact.fill(0);
            size_t pos = 3;
            for (int part = 0; part < 2; part++) {
                size_t len = der[pos++];
                size_t skip = len > 32 ? len - 32 : 0;
                std::copy(der.begin() + pos + skip, der.begin() + pos + len, compact.begin() + part * 32 + (32 - (len - skip)));
                pos += len + 1;
            }
            BOOST_CHECK_EQUAL(HexStr(compact.begin(), compact.end()), v["sig"].get_str());
        }
        // The 74-byte form in the file is EncodeAttestation of the parts.
        Attestation att;
        att.seq = v["seq"].get_int();
        att.priceMicroUsd = (uint32_t)v["priceMicroUsd"].get_int64();
        att.citedHeight = (uint32_t)v["citedHeight"].get_int64();
        att.sig = sig;
        BOOST_CHECK_EQUAL(HexStr(EncodeAttestation(att)), v["attestation"].get_str());
    }
}

// Rule: BUNDLE-1
BOOST_AUTO_TEST_CASE(highs_rejected)
{
    // A high-S encoding of a valid signature is invalid, never normalised (R17): the low-S form of the
    // same (r, s) verifies, the high-S form does not, and CPubKey::Verify would have accepted both.
    UniValue doc = Vectors();
    int seen = 0;
    for (const UniValue& v : doc["valid"].getValues()) {
        const uint256 msg = Internal32(v["message"].get_str());
        const CPubKey pk(ParseHex(v["pubkey"].get_str()));
        BOOST_CHECK(VerifyCompactSig(pk, msg, Sig64(v["sig"].get_str())));
        BOOST_CHECK(!VerifyCompactSig(pk, msg, Sig64(v["sigHighS"].get_str())));
        BOOST_CHECK(v["sig"].get_str() != v["sigHighS"].get_str());
        BOOST_CHECK_EQUAL(v["sig"].get_str().substr(0, 64), v["sigHighS"].get_str().substr(0, 64));   // same r
        seen++;
    }
    BOOST_CHECK_EQUAL(seen, 8);
    // Hand-made: s exactly n/2 + 1 is high, n/2 is not (both fail verification of course, but the low one gets as far as the curve check).
    for (const UniValue& v : doc["invalid"].getValues()) {
        if (v["name"].get_str() != "high_s") continue;
        BOOST_CHECK(!VerifyCompactSig(CPubKey(ParseHex(v["pubkey"].get_str())),
                                      AttestMessage(v["seq"].get_int(), (uint32_t)v["priceMicroUsd"].get_int64(), (uint32_t)v["citedHeight"].get_int64(),
                                                    Internal32(v["blockHashInternal"].get_str())),
                                      Sig64(v["sig"].get_str())));
    }
}

// Rule: BUNDLE-1
BOOST_AUTO_TEST_CASE(invalid_vectors_rejected)
{
    UniValue doc = Vectors();
    std::set<std::string> names;
    for (const UniValue& v : doc["invalid"].getValues()) {
        const uint256 msg = AttestMessage(v["seq"].get_int(), (uint32_t)v["priceMicroUsd"].get_int64(), (uint32_t)v["citedHeight"].get_int64(),
                                          Internal32(v["blockHashInternal"].get_str()));
        BOOST_CHECK_MESSAGE(!VerifyCompactSig(CPubKey(ParseHex(v["pubkey"].get_str())), msg, Sig64(v["sig"].get_str())), v["name"].get_str());
        names.insert(v["name"].get_str());
    }
    BOOST_CHECK(names.count("high_s"));
    BOOST_CHECK(names.count("wrong_block_hash"));
    BOOST_CHECK(names.count("wrong_key"));
    // Degenerate inputs: an invalid key, an uncompressed key, an all-zero and an all-0xff signature.
    const UniValue& v0 = doc["valid"][0];
    const uint256 msg = Internal32(v0["message"].get_str());
    const std::array<unsigned char, 64> sig = Sig64(v0["sig"].get_str());
    BOOST_CHECK(!VerifyCompactSig(CPubKey(), msg, sig));
    CKey unc;
    unc = CKey::TestOnlyRandomKey(false);
    BOOST_CHECK(!VerifyCompactSig(unc.GetPubKey(), msg, sig));
    std::array<unsigned char, 64> zero;
    zero.fill(0);
    BOOST_CHECK(!VerifyCompactSig(CPubKey(ParseHex(v0["pubkey"].get_str())), msg, zero));
    std::array<unsigned char, 64> ff;
    ff.fill(0xff);
    BOOST_CHECK(!VerifyCompactSig(CPubKey(ParseHex(v0["pubkey"].get_str())), msg, ff));
    // A fresh key signing through CKey (DER) then converted verifies; a flipped bit does not.
    CKey k;
    k = CKey::TestOnlyRandomKey(true);
    std::vector<unsigned char> der;
    BOOST_REQUIRE(k.Sign(msg, der));
    std::array<unsigned char, 64> compact;
    compact.fill(0);
    size_t pos = 3;
    for (int part = 0; part < 2; part++) {
        size_t len = der[pos++];
        size_t skip = len > 32 ? len - 32 : 0;
        std::copy(der.begin() + pos + skip, der.begin() + pos + len, compact.begin() + part * 32 + (32 - (len - skip)));
        pos += len + 1;
    }
    BOOST_CHECK(VerifyCompactSig(k.GetPubKey(), msg, compact));
    compact[40] ^= 1;
    BOOST_CHECK(!VerifyCompactSig(k.GetPubKey(), msg, compact));
}

// Rule: BUNDLE-1
// The flat "vectors" list shared with the Python framework: every row's attestation bytes decode, and verify iff `valid`.
BOOST_AUTO_TEST_CASE(shared_vector_list)
{
    UniValue doc = Vectors();
    const UniValue& rows = doc["vectors"];
    BOOST_REQUIRE(rows.isArray());
    int valid = 0, invalid = 0, regtest = 0;
    for (const UniValue& r : rows.getValues()) {
        std::optional<Attestation> att = DecodeAttestation(ParseHex(r["attestation"].get_str()));
        BOOST_REQUIRE(att);
        BOOST_CHECK_EQUAL(att->seq, r["seq"].get_int());
        BOOST_CHECK_EQUAL(att->priceMicroUsd, (uint32_t)r["price"].get_int64());
        BOOST_CHECK_EQUAL(att->citedHeight, (uint32_t)r["citedHeight"].get_int64());
        const uint256 blockHash = uint256S(r["blockHash"].get_str());   // the display form; uint256S reverses into internal bytes
        const uint256 msg = AttestMessage(att->seq, att->priceMicroUsd, att->citedHeight, blockHash);
        const CPubKey pk(ParseHex(r["pubkey"].get_str()));
        const bool ok = VerifyCompactSig(pk, msg, att->sig);
        BOOST_CHECK_MESSAGE(ok == r["valid"].get_bool(), r["attestation"].get_str());
        if (r["valid"].get_bool()) {
            valid++;
            // The secret re-derives the key and, through libsecp256k1's RFC 6979, the very same signature.
            std::vector<unsigned char> secret = ParseHex(r["secret"].get_str());
            CKey key;
            key.Set(secret.begin(), secret.end(), true);
            BOOST_REQUIRE(key.IsValid());
            BOOST_CHECK(key.GetPubKey() == pk);
            std::vector<unsigned char> der;
            BOOST_REQUIRE(key.Sign(msg, der));
            std::array<unsigned char, 64> compact;
            compact.fill(0);
            size_t pos = 3;
            for (int part = 0; part < 2; part++) {
                size_t len = der[pos++];
                size_t skip = len > 32 ? len - 32 : 0;
                std::copy(der.begin() + pos + skip, der.begin() + pos + len, compact.begin() + part * 32 + (32 - (len - skip)));
                pos += len + 1;
            }
            BOOST_CHECK(compact == att->sig);
        } else {
            invalid++;
        }
        if (r.exists("name") && r["name"].get_str().rfind("regtest-attestor-0", 0) == 0) {
            regtest++;
            BOOST_CHECK_EQUAL(r["pubkey"].get_str(), "0219ce7f2f737be07548a7243c605b76a09e039942f58ef91fe52771bf1f88767b");
            BOOST_CHECK_EQUAL(r["blockHash"].get_str(), std::string(62, '0') + "01");
            BOOST_CHECK_EQUAL(*(blockHash.begin()), 1);   // internal bytes: 01 then 31 zeros
            BOOST_CHECK(ok);
        }
    }
    BOOST_CHECK_EQUAL(valid, 10);
    BOOST_CHECK_EQUAL(invalid, 5);
    BOOST_CHECK_EQUAL(regtest, 2);
}

// Rule: BUNDLE-1
BOOST_AUTO_TEST_CASE(codec)
{
    Attestation a;
    a.seq = 0xBEEF;
    a.priceMicroUsd = 0x01020304;
    a.citedHeight = 0x0A0B0C0D;
    for (int i = 0; i < 64; i++) a.sig[i] = (unsigned char)(0x40 + i);
    std::vector<unsigned char> enc = EncodeAttestation(a);
    BOOST_REQUIRE_EQUAL(enc.size(), ATTESTATION_SIZE);
    BOOST_CHECK_EQUAL(ATTESTATION_SIZE, 74u);
    const unsigned char head[10] = { 0xEF, 0xBE, 0x04, 0x03, 0x02, 0x01, 0x0D, 0x0C, 0x0B, 0x0A };
    BOOST_CHECK(std::equal(head, head + 10, enc.begin()));
    BOOST_CHECK(std::equal(a.sig.begin(), a.sig.end(), enc.begin() + 10));
    std::optional<Attestation> d = DecodeAttestation(enc);
    BOOST_REQUIRE(d);
    BOOST_CHECK(*d == a);
    BOOST_CHECK(EncodeAttestation(*d) == enc);
    // Any other length is refused.
    BOOST_CHECK(!DecodeAttestation(std::vector<unsigned char>()));
    BOOST_CHECK(!DecodeAttestation(std::vector<unsigned char>(enc.begin(), enc.end() - 1)));
    enc.push_back(0);
    BOOST_CHECK(!DecodeAttestation(enc));
    BOOST_CHECK(!DecodeAttestation(nullptr, 74));
}

BOOST_AUTO_TEST_SUITE_END()
