#!/usr/bin/env python3
# Copyright (c) 2026 The Ycash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .

"""
Writes src/test/data/vault_vectors.json, the golden vector of the vault primitive
(docs/plans/yellowback-upgrade-plan.md §15.9), deterministically from fixed private keys.
src/test/vault_vectors_tests.cpp replays it against the C++; the file must be byte-identical
on both node lines (ycash-dd and ycash6).

    .venv/bin/python qa/rpc-tests/test_framework/gen_vault_vectors.py           # write
    .venv/bin/python qa/rpc-tests/test_framework/gen_vault_vectors.py --check   # compare only

JSON schema (top-level keys; every byte string is lowercase hex; ids, txids, set ids and
hashes are the **internal** byte order = uint256::begin()..end() unless the key ends in
"Display"; a prevout is the 36-byte COutPoint serialisation, txid internal || n u32 LE):

    _comment, _schema        text
    branchId                 int, 0x6d5b7a31 (signatures in "spends" use it)
    opcodes                  {"CHECKSEQUENCEVERIFY": 178, "CHECKSETSIG": 192, "CHECKSETDORMANT": 193}
    keys[]                   {label, secret (32), pubkey (33, compressed)}
    vaults[]                 {name, params {tag, setId, cancelSetId, delay, ownerHeight, appHeight,
                              ownerKey}, script}               ParseVault(script) == params,
                                                               BuildVault(params) == script
    vaultsInvalid[]          {name, script, reason}           ParseVault(script) fails
    intents[]                {name, params {tag, recipientHash, vaultHash, delay, cancelSetId, setId,
                              ownerKey}, script, recipientScript?, vaultScript?}
    intentsInvalid[]         {name, script, reason}
    bonds[]                  {memberKey, locktime, redeem, spk (P2SH of redeem)}
    selectors[]              {kind "V"|"I", scriptSig, selector, nArgs}
    selectorsInvalid[]       {kind, scriptSig, reason}
    acts[]                   {name, type, fields (decoded, as decode_act), payload, prevout, actMsg,
                              signers [key labels], sigs [65], recovered [33], script (the OP_RETURN),
                              convicts? (SET_EQUIVOCATION: the key both signatures recover to)}
    actsInvalid[]            {name, payload, reason, stage}   stage "decode": magic / version / type /
                              size, DecodePayload fails; stage "field": a context-free field rule of
                              15.5 (CREATE ranges and flags, bondLocktime, burn, roles, signature
                              header) -- Python rejects it at decode, C++ may at rule time
    actScriptsInvalid[]      {name, script, reason}           the act output is malformed
    setSigMsgs[]             {setId, role, prevout, sighash, msg}
    signatures[]             {label, secret, pubkey, msg, sig, lowSFlipped}
                              sig == CKey::SignCompact(uint256(msg)); RecoverSetSig(msg, sig) == pubkey
    signaturesInvalid[]      {name, msg, sig, reason, nonStrictRecovers (pubkey or null)}
                              RecoverSetSig (strict: header 31..34, low S) fails
    spends[]                 {name, tx (final hex), nIn, scriptCode, amount, branchId, sighash,
                              setId, role, setSigMsg, signers, sigs, scriptSig}
                              SignatureHash(scriptCode, tx, nIn, SIGHASH_ALL, amount, branchId) == sighash

"reason" strings are informative (the Python codes); a C++ test asserts only rejection.
"""

import json
import os
import sys

if __name__ == '__main__':
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

from test_framework import vault as v    # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', '..', '..'))
OUT = os.path.join(ROOT, 'src', 'test', 'data', 'vault_vectors.json')

LABELS = ['admit', 'owner', 'member-0', 'member-1', 'member-2', 'member-3', 'member-4', 'outsider']


def _keys():
    return {lab: v.fixed_secret('vault-vectors-' + lab) for lab in LABELS}


def _h(b):
    return bytes(b).hex()


def _txid(label):
    """A fixed txid (display hex) from a label."""
    return v.sha256(b'vault-vectors-txid-' + label.encode())[::-1].hex()


def build():
    K = _keys()
    P = {lab: v.pubkey_of(s) for lab, s in K.items()}
    set_a = v.txid_internal(_txid('set-a'))
    set_b = v.txid_internal(_txid('set-b'))
    doc = {
        '_comment': 'Generated by qa/rpc-tests/test_framework/gen_vault_vectors.py; do not edit. '
                    'Schema in that file and in qa/rpc-tests/test_framework/VAULT_VECTORS.md.',
        '_schema': 'hex everywhere; ids/hashes internal byte order (uint256::begin()); prevout = txid internal || n u32 LE; '
                   'integers in act bodies little-endian; script numbers minimal (CScript << int64_t).',
        'branchId': v.VAULT_BRANCH_ID,
        'opcodes': {'CHECKSEQUENCEVERIFY': v.OP_CHECKSEQUENCEVERIFY, 'CHECKSETSIG': v.OP_CHECKSETSIG,
                    'CHECKSETDORMANT': v.OP_CHECKSETDORMANT},
        'keys': [{'label': lab, 'secret': _h(K[lab]), 'pubkey': _h(P[lab])} for lab in LABELS],
    }

    # --- vaults
    def vp(**kw):
        d = dict(tag=b'WYEC', set_id=set_a, cancel_set_id=set_b, delay=144, owner_height=1000, app_height=0,
                 owner_key=P['owner'])
        d.update(kw)
        return v.VaultParams(**d)

    off_curve = b'\x02' + bytes(31) + b'\x07'
    while v.is_valid_point(off_curve):
        off_curve = off_curve[:-1] + bytes([off_curve[-1] + 1])
    vault_cases = [
        ('bridge-default', vp()),
        ('delay-1-opcode', vp(delay=1)),
        ('delay-16-opcode', vp(delay=16)),
        ('delay-17-push', vp(delay=17)),
        ('delay-128-two-bytes', vp(delay=128)),
        ('delay-max', vp(delay=65535)),
        ('owner-height-1', vp(owner_height=1)),
        ('owner-height-max', vp(owner_height=499999999)),
        ('app-enabled', vp(tag=b'YED\x00', set_id=set_a, cancel_set_id=set_a, app_height=1288)),
        ('app-height-max', vp(app_height=499999999)),
        ('tag-zero', vp(tag=bytes(4))),
        ('owner-key-off-curve-accepted', vp(owner_key=off_curve)),     # A-2: prefix check only
    ]
    doc['vaults'] = [{'name': n, 'params': p.to_json(), 'script': _h(v.vault_script(p))} for n, p in vault_cases]

    base = v.vault_script(vp(delay=5))
    i_delay = 4 + 1 + 32 + 1
    good = v.vault_script(vp())
    k_set = good.rfind(set_a)
    j_oh = base.find(bytes([0x02, 0xe8, 0x03]))
    inv = [
        ('delay-0', v.vault_script_unchecked(vp(delay=0)), 'delay out of range'),
        ('delay-65536', v.vault_script_unchecked(vp(delay=65536)), 'delay out of range'),
        ('delay-negative', v.vault_script_unchecked(vp(delay=-1)), 'delay out of range'),
        ('delay-5-as-data-push', base[:i_delay] + b'\x01\x05' + base[i_delay + 1:], 'non-minimal number'),
        ('owner-height-padded', base[:j_oh] + bytes([0x03, 0xe8, 0x03, 0x00]) + base[j_oh + 3:], 'non-minimal number'),
        ('owner-height-0', v.vault_script_unchecked(vp(owner_height=0)), 'ownerHeight out of range'),
        ('owner-height-500000000', v.vault_script_unchecked(vp(owner_height=500000000)), 'ownerHeight out of range'),
        ('app-height-500000000', v.vault_script_unchecked(vp(app_height=500000000)), 'appHeight out of range'),
        ('owner-key-uncompressed-prefix', v.vault_script_unchecked(vp(owner_key=b'\x04' + P['owner'][1:])), 'ownerKey'),
        ('setid-copies-differ', good[:k_set] + set_b + good[k_set + 32:], 'shape'),
        ('pushdata1-for-32-bytes', good[:5] + bytes([v.OP_PUSHDATA1]) + good[5:], 'non-minimal push'),
        ('trailing-op', good + bytes([v.OP_1]), 'shape'),
        ('truncated', good[:-1], 'shape'),
        ('empty', b'', 'shape'),
        ('tag-5-bytes', bytes([5]) + b'WYECX' + good[5:], 'shape'),
    ]
    for n, s, _r in inv:
        assert v.parse_vault(s) is None, n
    doc['vaultsInvalid'] = [{'name': n, 'script': _h(s), 'reason': r} for n, s, r in inv]

    # --- intents
    recipient = v.p2pkh_script_of_pubkey(P['member-4'])
    intents = []
    for n, p in [('bridge-default', vp()), ('delay-1', vp(delay=1)), ('app-enabled', vault_cases[8][1])]:
        ip = v.intent_for(p, recipient)
        intents.append({'name': n, 'params': ip.to_json(), 'script': _h(v.intent_script(ip)),
                        'recipientScript': _h(recipient), 'vaultScript': _h(v.vault_script(p))})
    doc['intents'] = intents
    ip0 = v.intent_for(vp(), recipient)
    igood = v.intent_script(ip0)
    ibad = [
        ('delay-0', v.intent_script_unchecked(v.IntentParams(ip0.tag, ip0.recipient_hash, ip0.vault_hash, 0,
                                                             ip0.cancel_set_id, ip0.set_id, ip0.owner_key)), 'delay'),
        ('delay-65536', v.intent_script_unchecked(v.IntentParams(ip0.tag, ip0.recipient_hash, ip0.vault_hash, 65536,
                                                                 ip0.cancel_set_id, ip0.set_id, ip0.owner_key)), 'delay'),
        ('trailing-byte', igood + b'\x00', 'shape'),
        ('vault-is-not-intent', v.vault_script(vp()), 'shape'),
        ('role-1-in-cancel-branch', igood.replace(bytes([v.OP_2, v.OP_CHECKSETSIG]), bytes([v.OP_1, v.OP_CHECKSETSIG])),
         'shape'),
    ]
    for n, s, _r in ibad:
        assert v.parse_intent(s) is None, n
    doc['intentsInvalid'] = [{'name': n, 'script': _h(s), 'reason': r} for n, s, r in ibad]

    # --- bonds
    doc['bonds'] = [{'memberKey': _h(P['member-0']), 'locktime': lt, 'redeem': _h(v.bond_script(P['member-0'], lt)),
                     'spk': _h(v.bond_spk(P['member-0'], lt))} for lt in (16, 1300, 499999999)]

    # --- selectors
    s65 = bytes([31]) + bytes(64)
    sel = [
        ('V', v.vault_unlock_scriptsig([s65, s65]), 1, 2),
        ('V', v.vault_owner_scriptsig(b'\x30\x06' + bytes(6) + b'\x01'), 2, 1),
        ('V', v.vault_owner_released_scriptsig(b'\x30\x06' + bytes(6) + b'\x01'), 3, 1),
        ('V', v.vault_app_scriptsig(), 4, 0),
        ('I', v.intent_release_scriptsig(), 1, 0),
        ('I', v.intent_cancel_scriptsig([s65]), 2, 1),
        ('I', v.intent_owner_released_scriptsig(b'\x30\x06' + bytes(6) + b'\x01'), 3, 1),
    ]
    for kind, ss, s_, n in sel:
        assert v.parse_selector(ss, kind) == (s_, v.push_values(ss)[:-1]) and n == len(v.push_values(ss)) - 1
    doc['selectors'] = [{'kind': k, 'scriptSig': _h(ss), 'selector': s_, 'nArgs': n} for k, ss, s_, n in sel]
    sel_bad = [
        ('V', bytes([0x55]), 'OP_5 is not a selector'),
        ('I', bytes([v.OP_4]), 'OP_4 is not an intent selector'),
        ('V', b'\x01\x01', 'selector pushed as data'),
        ('V', b'', 'empty'),
        ('V', bytes([v.OP_0]), 'OP_0'),
        ('V', bytes([v.OP_1NEGATE]), 'OP_1NEGATE'),
        ('V', bytes([v.OP_DUP, v.OP_1]), 'not push-only'),
        ('V', b'\x02\xaa', 'truncated push'),
    ]
    for kind, ss, _r in sel_bad:
        assert v.parse_selector(ss, kind) is None
    doc['selectorsInvalid'] = [{'kind': k, 'scriptSig': _h(ss), 'reason': r} for k, ss, r in sel_bad]

    # --- acts
    prevout_txid, prevout_n = _txid('act-funding'), 3
    po36 = v.ser_prevout(prevout_txid, prevout_n)
    sighash_a, sighash_b = v.sha256(b'vault-vectors-sighash-a'), v.sha256(b'vault-vectors-sighash-b')
    eqv = v.equivocation_proof(set_a, K['member-2'], _txid('contested'), 1, v.ROLE_UNLOCK, sighash_a,
                               v.ROLE_CANCEL, sighash_b)
    act_cases = [
        ('set-create', v.act_set_create(7, 5, 1, 5, P['admit'], flags=0, rate_limit_bps=1000, rate_window=1008,
                                        liveness_window=4032, bond_min=50 * v.COIN, bond_lock_min=8064, maturity=144),
         []),
        ('set-create-open-max', v.act_set_create(15, 15, 15, 15, P['admit'], flags=v.SET_FLAG_OPEN,
                                                 rate_limit_bps=10000, rate_window=1048576, liveness_window=1,
                                                 bond_min=21000000 * v.COIN, bond_lock_min=0xFFFFFFFF,
                                                 maturity=0xFFFFFFFF), []),
        ('set-join-admit', v.act_set_join(set_a, P['member-0'], 2000, 0), ['member-0', 'admit']),
        ('set-join-members', v.act_set_join(set_a, P['member-3'], 499999999, 2),
         ['member-3', 'member-0', 'member-1']),
        ('set-heartbeat', v.act_set_heartbeat(set_a, P['member-1']), ['member-1']),
        ('set-remove-return', v.act_set_remove(set_a, P['member-4'], 0), ['member-0', 'member-1']),
        ('set-remove-burn', v.act_set_remove(set_a, P['member-4'], 1), ['member-0', 'member-1']),
        ('set-equivocation', eqv, []),
        ('set-winddown', v.act_set_winddown(set_a), ['member-0', 'member-1', 'member-2']),
        ('set-create-admit-key-off-curve-accepted', v.act_set_create(1, 1, 1, 1, off_curve), []),   # A-2
        ('set-join-member-key-off-curve-accepted', v.act_set_join(set_a, off_curve, 2000, 0), []),   # A-2
    ]
    acts = []
    for n, a, signers in act_cases:
        p = v.encode_act(a)
        msg = v.act_msg(p, prevout_txid, prevout_n)
        sigs = [v.sign_recoverable(K[s], msg) for s in signers]
        rec = [v.recover_compact(s, msg) for s in sigs]
        assert rec == [P[s] for s in signers]
        script = v.act_script(p, sigs)
        assert len(script) <= v.ACT_MAX_SCRIPT and v.parse_act_script(script)[0] == p
        fields = v.decode_act(p)
        fields.pop('name')
        e = {'name': n, 'type': a['type'], 'fields': fields, 'payload': _h(p), 'prevout': _h(po36),
             'actMsg': _h(msg), 'signers': signers, 'sigs': [_h(s) for s in sigs], 'recovered': [_h(r) for r in rec],
             'script': _h(script)}
        if a['type'] == v.ACT_SET_EQUIVOCATION:
            e['convicts'] = _h(v.equivocation_key(a))
            assert e['convicts'] == _h(P['member-2'])
        acts.append(e)
    doc['acts'] = acts

    cp = v.encode_act(act_cases[0][1])
    create = act_cases[0][1]

    def bad_create(**kw):
        return v.encode_act(dict(create, **kw), check=False)
    join = act_cases[2][1]
    rem = act_cases[5][1]
    act_bad = [
        ('too-short', b'YV\x01', 'size'),
        ('bad-magic', b'YW' + cp[2:], 'magic'),
        ('version-0', b'YV\x00' + cp[3:], 'version'),
        ('version-2', b'YV\x02' + cp[3:], 'version'),
        ('type-0', b'YV\x01\x00' + cp[4:], 'type'),
        ('type-7', b'YV\x01\x07' + cp[4:], 'type'),
        ('create-truncated', cp[:-1], 'size'),
        ('create-trailing-byte', cp + b'\x00', 'size'),
        ('winddown-trailing-byte', v.encode_act(v.act_set_winddown(set_a)) + b'\x00', 'size'),
        ('seats-0', bad_create(seats=0, unlockThreshold=0, cancelThreshold=0, slashThreshold=0), 'seats'),
        ('seats-16', bad_create(seats=16), 'seats'),
        ('unlock-threshold-0', bad_create(unlockThreshold=0), 'threshold'),
        ('cancel-threshold-gt-seats', bad_create(cancelThreshold=8), 'threshold'),
        ('slash-threshold-gt-seats', bad_create(slashThreshold=8), 'threshold'),
        ('flags-bit1', bad_create(flags=2), 'flags'),
        ('rate-10001', bad_create(rateLimitBps=10001), 'rate'),
        ('rate-window-0', bad_create(rateWindow=0), 'window'),
        ('rate-window-1048577', bad_create(rateWindow=1048577), 'window'),
        ('liveness-window-0', bad_create(livenessWindow=0), 'window'),
        ('liveness-window-1048577', bad_create(livenessWindow=1048577), 'window'),
        ('bond-min-0', bad_create(bondMin=0), 'bondMin'),
        ('bond-min-negative', bad_create(bondMin=-1), 'bondMin'),
        ('bond-min-above-max-money', bad_create(bondMin=v.MAX_MONEY + 1), 'bondMin'),   # D-1
        ('admit-key-04', bad_create(admitKey='04' + create['admitKey'][2:]), 'key'),
        ('join-locktime-500000000', v.encode_act(dict(join, bondLocktime=500000000), check=False), 'locktime'),
        ('remove-burn-2', v.encode_act(dict(rem, burn=2), check=False), 'burn'),
        ('equivocation-role-0', v.encode_act(dict(eqv, roleA=0), check=False), 'role'),
        ('equivocation-role-3', v.encode_act(dict(eqv, roleB=3), check=False), 'role'),
        ('equivocation-sig-header-27', v.encode_act(dict(eqv, sigA='1b' + eqv['sigA'][2:]), check=False), 'sig header'),
    ]
    for n, p, _r in act_bad:
        try:
            v.decode_act(p)
            raise AssertionError('decoded ' + n)
        except v.VaultError:
            pass
    structural = ('size', 'magic', 'version', 'type')
    doc['actsInvalid'] = [{'name': n, 'payload': _h(p), 'reason': r, 'stage': 'decode' if r in structural else 'field'}
                          for n, p, r in act_bad]

    wd = v.encode_act(v.act_set_winddown(set_a))
    wsig = v.sign_recoverable(K['member-0'], v.act_msg(wd, prevout_txid, prevout_n))
    sc_bad = [
        ('pushdata1-for-short-payload', bytes([v.OP_RETURN, v.OP_PUSHDATA1, len(wd)]) + wd, 'non-minimal push'),
        ('sig-64-bytes', v.act_script(wd, [wsig[:64]]), 'signature size'),
        ('opcode-after-payload', v.act_script(wd) + bytes([v.OP_1]), 'non-push'),
        ('payload-undecodable', v.act_script(wd[:-1]), 'body'),
    ]
    for n, s, _r in sc_bad:
        try:
            v.parse_act_script(s)
            raise AssertionError(n)
        except v.VaultError:
            pass
    doc['actScriptsInvalid'] = [{'name': n, 'script': _h(s), 'reason': r} for n, s, r in sc_bad]

    # --- set-signature messages
    msgs = []
    for sid, role, txl, n, sh in [(set_a, 1, 'vault-1', 0, sighash_a), (set_a, 2, 'intent-1', 1, sighash_b),
                                  (set_b, 1, 'vault-2', 0xFFFFFFFF, sighash_a)]:
        po = v.ser_prevout(_txid(txl), n)
        msgs.append({'setId': _h(sid), 'role': role, 'prevout': _h(po), 'sighash': _h(sh),
                     'msg': _h(v.set_sig_msg_raw(sid, role, po, sh))})
    doc['setSigMsgs'] = msgs

    # --- signatures (include both low-S branches)
    sigs, seen = [], set()
    i = 0
    while len(sigs) < 8 or seen != {True, False}:
        lab = LABELS[i % len(LABELS)]
        msg = v.sha256(b'vault-vectors-msg-%d' % i)
        _r, _s, _rec, fl = v.ecdsa_sign_rec(K[lab], msg)
        seen.add(fl)
        if len(sigs) < 8 or fl not in {e['lowSFlipped'] for e in sigs}:
            sig = v.sign_recoverable(K[lab], msg)
            assert v.recover_compact(sig, msg) == P[lab]
            sigs.append({'label': lab, 'secret': _h(K[lab]), 'pubkey': _h(P[lab]), 'msg': _h(msg), 'sig': _h(sig),
                         'lowSFlipped': fl})
        i += 1
    doc['signatures'] = sigs
    base_sig = bytes.fromhex(sigs[0]['sig'])
    base_msg = bytes.fromhex(sigs[0]['msg'])
    r_, s_ = base_sig[1:33], int.from_bytes(base_sig[33:], 'big')
    sig_bad = [
        ('high-s', bytes([31 + ((base_sig[0] - 31) ^ 1)]) + r_ + (v._N - s_).to_bytes(32, 'big'), 'high S'),
        ('header-27-uncompressed', bytes([base_sig[0] - 4]) + base_sig[1:], 'header'),
        ('header-35', bytes([35]) + base_sig[1:], 'header'),
        ('header-30', bytes([30]) + base_sig[1:], 'header'),
        ('r-zero', base_sig[:1] + bytes(32) + base_sig[33:], 'r = 0'),
        ('s-zero', base_sig[:33] + bytes(32), 's = 0'),
        ('r-ge-n', base_sig[:1] + v._N.to_bytes(32, 'big') + base_sig[33:], 'r >= n'),
    ]
    out = []
    for n, s, r in sig_bad:
        assert v.recover_compact(s, base_msg) is None, n
        ns = v.recover_compact(s, base_msg, strict=False)
        out.append({'name': n, 'msg': _h(base_msg), 'sig': _h(s), 'reason': r,
                    'nonStrictRecovers': None if ns is None else _h(ns)})
    doc['signaturesInvalid'] = out

    # --- spends: full transactions, ZIP-243 sighash under the vault branch id, set signatures
    spends = []
    vp_u = vp(delay=10)
    v_out = (_txid('vault-utxo'), 0)
    fee_in = [(_txid('fee-utxo'), 1, v.SEQUENCE_FINAL)]
    value = 25 * v.COIN
    signers = ['member-0', 'member-1']
    utx = v.build_unlock_tx(v_out, vp_u, value, [(recipient, 20 * v.COIN)], relock_value=5 * v.COIN,
                            fee_vin=fee_in, change=(v.COIN, recipient), member_secrets=[K[s] for s in signers])
    v_spk = v.vault_script(vp_u)
    spends.append(_spend('unlock', utx, 0, v_spk, value, set_a, v.ROLE_UNLOCK, signers, K, P))
    i_spk = v.intent_script(v.intent_for(vp_u, recipient))
    ctx = v.build_cancel_tx((_txid('intent-utxo'), 0), v.intent_for(vp_u, recipient), 20 * v.COIN, vp_u,
                            fee_vin=fee_in, member_secrets=[K['member-2']])
    spends.append(_spend('cancel', ctx, 0, i_spk, 20 * v.COIN, set_b, v.ROLE_CANCEL, ['member-2'], K, P))
    doc['spends'] = spends
    return doc


def _spend(name, tx, n_in, spk, amount, set_id, role, signers, K, P):
    sh = v.template_sighash(tx, n_in, spk, amount)
    txid, n = v.prevout_of(tx, n_in)
    msg = v.set_sig_msg(set_id, role, txid, n, sh)
    sigs = [v.sign_recoverable(K[s], msg) for s in signers]
    sel = v.parse_selector(tx.vin[n_in].scriptSig, 'V' if role == v.ROLE_UNLOCK else 'I')
    assert sel[1] == sigs
    assert [v.recover_compact(s, msg) for s in sigs] == [P[s] for s in signers]
    return {'name': name, 'tx': v.tx_hex(tx), 'nIn': n_in, 'scriptCode': _h(spk), 'amount': amount,
            'branchId': v.VAULT_BRANCH_ID, 'sighash': _h(sh), 'setId': _h(set_id), 'role': role,
            'setSigMsg': _h(msg), 'signers': signers, 'sigs': [_h(s) for s in sigs],
            'scriptSig': _h(tx.vin[n_in].scriptSig)}


def dumps(doc):
    return json.dumps(doc, indent=1, sort_keys=False) + '\n'


def main():
    text = dumps(build())
    if '--check' in sys.argv[1:]:
        with open(OUT) as f:
            if f.read() != text:
                print('vault_vectors.json is stale; rerun without --check')
                return 1
        print('vault_vectors.json up to date')
        return 0
    with open(OUT, 'w') as f:
        f.write(text)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
