#!/usr/bin/env python3
# Copyright (c) 2026 The Ycash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .

"""Generate (or --check) the yed_* rows of rpc/common.h's rpcCvtTable (ycashd 6.20.0 port, seam S1).

6.20.0 replaced v4.5.0's client-side vRPCConvertParams with rpcCvtTable, which the server also
consults: a call whose argument count is not covered by an operation's {required},{optional}
vectors is rejected before the handler runs. So every yed_* RPC needs a row with its exact arity.

Arity comes from each handler's own `if (fHelp || params.size() ...)` guard in
src/rpc/yellowback.cpp and src/rpc/yellowbackwallet.cpp, the check the handler enforces.
(doc/yellowback-rpc-contract.json's `args` grammar is documentation and omits a few optional
arguments.) The JSON-typed positions are v4.5.0's src/rpc/client.cpp conversion rows, verbatim.

  qa/yellowback-rpc-cvt.py           rewrite the block between the markers in src/rpc/common.h
  qa/yellowback-rpc-cvt.py --check   exit 1 if the block is stale
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HANDLERS = [ROOT / "src/rpc/yellowback.cpp", ROOT / "src/rpc/yellowbackwallet.cpp"]
TABLE = ROOT / "src/rpc/common.h"
BEGIN = "    // yellowback: generated by qa/yellowback-rpc-cvt.py from the handlers' arity guards; do not edit by hand\n"
END = "    // end yellowback\n"

# v4.5.0 src/rpc/client.cpp: positions converted as JSON (numbers, objects, booleans).
JSON_POSITIONS = {
    "yed_buildbundle": {0}, "yed_claim": {3, 4, 5}, "yed_claimnotice": {2},
    "yed_estimatecollateral": {0, 1, 2}, "yed_estimatefee": {0}, "yed_estimatesend": {0},
    "yed_getfeepayee": {0, 1}, "yed_gethistory": {0, 1}, "yed_getprice": {0}, "yed_getselection": {0},
    "yed_getstatehash": {0}, "yed_listattestors": {0}, "yed_listclaimable": {0, 1}, "yed_listminers": {0, 1}, "yed_listtokens": {0, 1, 2, 3},
    "yed_listtransactions": {0, 1}, "yed_listvaults": {1, 2}, "yed_mint": {0, 1, 4, 5},
    "yed_registerattestor": {0, 1, 2}, "yed_reportequivocation": {2}, "yed_revive": {0, 1}, "yed_send": {1},
    "yed_sendmany": {0}, "yed_setquote": {0, 1}, "yed_signattestation": {0, 1, 2}, "yed_unlockcoin": {1},
    "yed_withdrawbond": {0},
}


def arities():
    out = {}
    for path in HANDLERS:
        fn = None
        for line in path.read_text().splitlines():
            m = re.match(r"^UniValue (yed_[a-z]+)\(", line)
            if m:
                fn = m.group(1)
                continue
            if fn and "fHelp ||" in line:
                g = line.split("fHelp ||", 1)[1]
                if (m := re.search(r"params\.size\(\) < (\d+) \|\| params\.size\(\) > (\d+)", g)):
                    lo, hi = int(m.group(1)), int(m.group(2))
                elif (m := re.search(r"params\.size\(\) != (\d+)", g)):
                    lo = hi = int(m.group(1))
                elif (m := re.search(r"params\.size\(\) > (\d+)", g)):
                    lo, hi = 0, int(m.group(1))
                else:
                    sys.exit(f"{path.name}: cannot read the arity guard of {fn}: {line.strip()}")
                out[fn] = (lo, hi)
                fn = None
    registered = set()
    for path in HANDLERS:
        registered |= set(re.findall(r'\{ *"[a-z]+", *"(yed_[a-z]+)"', path.read_text()))
    missing = registered - set(out)
    if missing:
        sys.exit(f"registered without a readable guard: {sorted(missing)}")
    return {k: v for k, v in out.items() if k in registered}


def block():
    rows = []
    for name, (lo, hi) in sorted(arities().items()):
        conv = ["o" if i in JSON_POSITIONS.get(name, set()) else "s" for i in range(hi)]
        req, opt = ", ".join(conv[:lo]), ", ".join(conv[lo:])
        rows.append(f'    {{ "{name}",{" " * max(1, 28 - len(name))}{{{{{req}}}, {{{opt}}}}} }},\n')
    return BEGIN + "".join(rows) + END


def main():
    text = TABLE.read_text()
    new = block()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        current = BEGIN + rest.split(END, 1)[0] + END
    else:
        head, tail = text.rsplit("};", 1)
        head, tail, current = head, "};" + tail, ""
    if "--check" in sys.argv:
        if current != new:
            sys.exit("rpc/common.h yed_* rows are stale: run qa/yellowback-rpc-cvt.py")
        print(f"rpc/common.h: {new.count(chr(10)) - 2} yed_* rows current")
        return
    TABLE.write_text(head + new + tail)
    print(f"wrote {new.count(chr(10)) - 2} yed_* rows to {TABLE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
