#!/usr/bin/env python3
# Copyright (c) 2026 The Ycash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .
"""Regenerate expected.json from scenarios.json with the Python aggregator (the reference).

    ../../../.venv/bin/python contrib/yellowback/attest/fixtures/expected.py

Both test suites assert these numbers; when they disagree the Python behaviour wins
(plan §5) and the Rust port is what gets fixed."""

import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("yellowback_price", os.path.join(HERE, "..", "..", "yellowback_price.py"))
yp = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(yp)


def fixture_table(scenario, sources, btc_sources):
    """URL -> fixture bytes (or an OSError for a null reply), from the per-name reply map."""
    table = {}
    for s in sources + btc_sources:
        f = scenario["replies"].get(s["name"])
        if f is None:
            table[s["url"]] = OSError("no reply (fixture: connection refused)")
        else:
            with open(os.path.join(HERE, f), "rb") as fh:
                table[s["url"]] = fh.read()
    return table


def run_scenario(scenario, now):
    sources = yp.normalize_sources(scenario["sources"])
    btc = yp.normalize_btc_sources(scenario.get("btc_usd_sources", []))
    table = fixture_table(scenario, sources, btc)
    feed = yp.PriceFeed(scenario["sources"], None, dict(yp.FEED_DEFAULTS, **scenario.get("settings", {})),
                        scenario.get("btc_usd_sources", []))

    def http(url, headers, timeout):
        reply = table.get(url)
        if reply is None:
            raise OSError("no fixture for %s" % url)
        if isinstance(reply, Exception):
            raise reply
        return reply

    feed._http_get = http
    real_time = yp.time.time
    yp.time.time = lambda: float(now)
    try:
        feed.poll(force=True)
        agg = feed.aggregate()
        r = feed.report()
    finally:
        yp.time.time = real_time
    per_source = {n: {"state": h["state"], "micro_usd": h["last_price_micro_usd"] if h["state"] == "ok" else None}
                  for n, h in r["sources"].items()}
    btc_per_source = {n: {"state": h["state"], "micro_usd": h["last_price_micro_usd"] if h["state"] == "ok" else None}
                      for n, h in r["btc_usd"]["sources"].items()}
    return {
        "name": scenario["name"],
        "median_micro_usd": None if agg is None else agg[0],
        "source_mask": None if agg is None else agg[1],
        "contributing": [] if agg is None else agg[2],
        "live_sources": r["live_sources"],
        "live_venues": r["live_venues"],
        "btc_reference_usd": r["btc_usd"]["reference_usd"],
        "btc_live": r["btc_usd"]["live"],
        "sources": per_source,
        "btc_usd_sources": btc_per_source,
    }


def main():
    with open(os.path.join(HERE, "scenarios.json")) as f:
        spec = json.load(f)
    out = {"_readme": "Generated by expected.py from scenarios.json with the Python aggregator; do not edit by hand.",
           "now": spec["now"], "scenarios": [run_scenario(s, spec["now"]) for s in spec["scenarios"]]}
    with open(os.path.join(HERE, "expected.json"), "w") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    for s in out["scenarios"]:
        print("%-36s median %-8s mask %-5s from %s" % (s["name"], s["median_micro_usd"], s["source_mask"], ",".join(s["contributing"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
